<a href="https://colab.research.google.com/github/Hungk66tntoan/Hungk66tntoan/blob/main/MML2024_Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mathematics for machine learning,  **
## **Homework 1 : Python basics**

In this homework, you will be introduced with the Python programming language. You can run the examples as you like, but you will need to submit your solution for the four exercises.




---

### 1 Input/Output
In this exercise, we will learn how to print in Python to the standard output. Printing is as easy as calling the function `print`.

In [ ]:
print("Hello World!")

Hello World!


We can also print by just typing what we want to show. There is a difference with `print` but you will notice later.

In [ ]:
"Hello World!"

'Hello World!'

In the above example, a string `"Hello World!"` is being printed to the standard output. We might not use this a lot in our class, but if you are curious, this is an example of taking input from the standard input.

In [ ]:
x = input()
print(x)

Mathematics
Mathematics


### 2 Types

There are different types in Python. Here, we will introduce you to some of the basic ones.

In [ ]:
type(1)

int

In [ ]:
type(1.5)

float

In [ ]:
type("Hello World!")

str

In [ ]:
type(True)

bool

### 3 Variables

The literals that are introduced in exercise 2 can be stored in variables to be later accessed by using names.

In [ ]:
a = 1
print(a)

1


### 4 Operators

You might be familiar with operators like addition, subtraction, and others. We have them in Python too.

In [ ]:
2 + 5 # addition

7

In [ ]:
2 * 5 # multiplication

10

In [ ]:
2 ** 5 # power

32

In [ ]:
2 - 5 # subtraction

-3

In [ ]:
5 / 2 # division

2.5

In [ ]:
5 // 2 # integer division

2

In [ ]:
5 % 2 # modulo

1

In [ ]:
5 == 2 # equality

False

In [ ]:
5 != 2 # inequality

True

In [ ]:
5 > 2 # greater than

True

In [ ]:
5 >= 2 # greater than or equal

True

In [ ]:
5 < 2 # less than

False

In [ ]:
5 <= 2 # less than or equal

False

In [ ]:
5 <= 2 or 2 <= 5 # or

True

In [ ]:
5 <= 2 and 2 <= 5 # and

False

In [ ]:
not (5 <= 2)

True

Now, let's try to write a complicated formula. The closed form of the $n$-th Fibonacci number is $\frac{\varphi^n - (-\varphi)^{-n}}{\sqrt{5}}$ where $\varphi = \frac{1 + \sqrt{5}}{2}$ (source: https://en.wikipedia.org/wiki/Fibonacci_number#Closed-form_expression). Let's use this to compute the tenth Fibonacci number. Here, we also use `sqrt` from the `math` module which computes the square root. Notice that the result is not perfectly an integer due to the floating point precision. But this is good enough. We can also round the number using `round`.

In [ ]:
import math

phi = (1 + math.sqrt(5)) / 2
print((phi ** 10 - (-phi) ** -10) / math.sqrt(5))
print(round((phi ** 10 - (-phi) ** -10) / math.sqrt(5)))

55.000000000000014
55


### 5 Conditional

We often need our code to behave differently according to some condition. In Python, we can use `if` clause.

In [ ]:
n = 5
if n % 2 == 0:
  print("Even")
else:
  print("Odd")

Odd


In [ ]:
n = 8
modulo = n % 3
if modulo == 0:
  print("Zero")
elif modulo == 1:
  print("One")
else:
  print("Two")

Two


### 6 For Loop

Imagine that we want to print all the even numbers between 1 and 10. A natural way to do this is using a `for` loop.

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(2, 10):
  print(i)

2
3
4
5
6
7
8
9


In [ ]:
for i in range(1, 11, 2):
  print(i)

1
3
5
7
9


In [ ]:
for i in range(2, 11, 2):
  print(i) # even numbers between 1 to 10.

2
4
6
8
10


In [ ]:
for i in range(1, 11):
  if i % 2 == 0:
    print(i)

2
4
6
8
10


In [ ]:
for i in range(10, 0, -2):
  print(i)

10
8
6
4
2


Now, try to use `for` loop to write the first 10 Fibonacci numbers using the closed form that is given in Exercise 4.

In [ ]:
import math

for n in range(1, 11):
  phi = (1 + math.sqrt(5)) / 2
  print(round((phi ** n - (-phi) ** -n) / math.sqrt(5)))


1
1
2
3
5
8
13
21
34
55


Next, try to use `for` and `if` to check if 9999991 is a prime number.

In [ ]:
n = 9999991
is_prime = True
for i in range(2, n):
  if n % i == 0:
    is_prime = False
    break
print(is_prime)

True


### 7 List

We can create a list as follow:

In [ ]:
anything = [1, 5.0, "A string"]

In [ ]:
for i in range(3):
  print(anything[i])

1
5.0
A string


In [ ]:
for a in anything:
  print(a)

1
5.0
A string


In [ ]:
print(anything[0])
print(anything[1])
print(anything[2])

1
5.0
A string


Next, we will use list to construct a 2-dimensional structure such as a matrix or a Tic-Tac-Toe grid in Homework 1.

In [ ]:
M = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]
print(M)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]


In [ ]:
for i in range(5):
  for j in range(3):
    print(M[i][j], end=" ")
  print()

1 2 3 
4 5 6 
7 8 9 
10 11 12 
13 14 15 


Next, we will transpose the matrix above just using a `for` loop.

In [ ]:
for i in range(3):
  for j in range(5):
    print(M[j][i], end=" ")
  print()

1 4 7 10 13 
2 5 8 11 14 
3 6 9 12 15 


The following example shows a Tic-Tac-Toe grid. (https://en.wikipedia.org/wiki/Tic-tac-toe)

In [ ]:
grid = [["O", " ", " "],
        ["X", " ", " "],
        [" ", "X", "O"]]

Next, let's try to change the element in `(2,1)` (remember, index starts with 0) to `O`.

In [ ]:
grid[2][1] = 'O'

And then, we see the result.

In [ ]:
for i in range(3):
  for j in range(3):
    print(grid[i][j], end="")
  print()

O  
X  
 OO


The board looks a bit weird due to the spaces. Let's format it a bit better.

In [ ]:
print("-------")
for i in range(3):
  print(end="|")
  for j in range(3):
    print(grid[i][j], end="|")
  print()
  print("-------")

-------
|O| | |
-------
|X| | |
-------
| |X|O|
-------


One thing to note is, a variable assignment on lists will not copy the list. This might sound confusing but consider the following example.

In [ ]:
l1 = [1, 2, 3]
l2 = l1
l2[1] = 5
print(l1)
print(l2)

[1, 5, 3]
[1, 5, 3]


Both lists `l1` and `l2` are modified! This is because the variable `l1` and `l2` refer to the same list after `l2 = l1`. If you want `l2` to be a copy of `l1`, you need to use `copy` from the `copy` library.

In [ ]:
import copy

l1 = [1, 2, 3]
l2 = copy.copy(l1)
l2[1] = 5
print(l1)
print(l2)

[1, 2, 3]
[1, 5, 3]


Less obviously, consider the 2-dimensional case as in the Tic-Tac-Toe grid.

In [ ]:
grid1 = [["O", " ", " "],
         ["X", " ", " "],
         [" ", "X", "O"]]

Let's try to make a copy of `grid1` and modify an element of it.

In [ ]:
grid2 = copy.copy(grid1)
grid2[1][1] = "O"

Now, let's check the result.

In [ ]:
print(grid1)
print(grid2)

[['O', ' ', ' '], ['X', 'O', ' '], [' ', 'X', 'O']]
[['O', ' ', ' '], ['X', 'O', ' '], [' ', 'X', 'O']]


Notice that `grid1` was also changed! We have used `copy.copy`, but why? It's because a `grid1` is a list of list. Each element of `grid1` is a reference to the list. The `copy.copy` only copies the list references. Let's look at this example instead.

In [ ]:
grid2[1] = [" ", " ", " "]
print(grid1)
print(grid2)

[['O', ' ', ' '], ['X', 'O', ' '], [' ', 'X', 'O']]
[['O', ' ', ' '], [' ', ' ', ' '], [' ', 'X', 'O']]


Now, `grid1` and `grid2` are different because we modify the actual element of `grid2`. So, what should we do if we want to copy the entire 2-dimensional structure?

In [ ]:
grid2=copy.deepcopy(grid1)
grid2[1][2] = 'O'
print(grid1)
print(grid2)

[['O', ' ', ' '], ['X', 'O', ' '], [' ', 'X', 'O']]
[['O', ' ', ' '], ['X', 'O', 'O'], [' ', 'X', 'O']]


Let's look at a more complicated example. Let's try to print the first 10 Fibonacci numbers in a different way. We know that the Fibonacci number also satisfies the recurrence relation $F_n = F_{n-1} + F_{n-2}$ with $F_1 = F_2 = 1$.

In [ ]:
Fibonacci = [1, 1]
for i in range(2, 10):
  Fibonacci.append(Fibonacci[i - 1] + Fibonacci[i - 2])
print(Fibonacci)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


Now, let's try to construct the first few rows of Pascal's triangle (https://en.wikipedia.org/wiki/Pascal%27s_triangle)

In [ ]:
Pascal = [[1]]
for i in range(1, 10):
  Pascal.append([])
  Pascal[-1].append(1)
  for j in range(1, i):
    Pascal[-1].append(Pascal[-2][j - 1] + Pascal[-2][j])
  Pascal[-1].append(1)
for row in Pascal:
  for number in row:
    print(number, end = " ")
  print()

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1 
1 6 15 20 15 6 1 
1 7 21 35 35 21 7 1 
1 8 28 56 70 56 28 8 1 
1 9 36 84 126 126 84 36 9 1 


### ⭐ **Exercise 1**
It is known that the sum of the diagonal of Pascal's triangle is actually a Fibonacci number (https://en.wikipedia.org/wiki/Pascal%27s_triangle#Overall_patterns_and_properties). Write a code to verify this by printing the first 10 sum of such diagonals from the Pascal table that we just constructed.

In [ ]:
# Write your code here.

### ⭐ **Exercise 2**
Write a code that accepts two inputs `m` and `n` and create a matrix (list of list) with dimension `m x n` (where `m` is the number of rows and `n` is the number of columns) that contains a spiral of numbers starting from the top left spiralling to the center of the matrix. For example, when `m=4` and `n=5`, your program should compute the following matrix.

In [ ]:
import numpy
M = [[1, 2, 3, 4, 5], [14, 15, 16, 17, 6], [13, 20, 19, 18, 7], [12, 11, 10, 9, 8]]
# We use numpy.array just for formatting.
print(numpy.array(M))

[[ 1  2  3  4  5]
 [14 15 16 17  6]
 [13 20 19 18  7]
 [12 11 10  9  8]]


In [ ]:
# Your code here.

### 8 Functions

Imagine that there are 5 places in our code where we need to compute the Fibonacci number using the closed form that is introduced in Exercise 4. The code will looks like:

In [ ]:
import math

phi = (1 + math.sqrt(5)) / 2
print(round((phi ** 10 - (-phi) ** -10) / math.sqrt(5)))

# Some other code

phi = (1 + math.sqrt(5)) / 2
print(round((phi ** 20 - (-phi) ** -20) / math.sqrt(5)))

# Some other code

phi = (1 + math.sqrt(5)) / 2
print(round((phi ** 5 - (-phi) ** -5) / math.sqrt(5)))

55
6765
5


This is very tedious. It will be nice if we don't need to repeatedly type the formula (A keen reader might notice that we don't really need to redeclare `phi` multiple times in the above code, but that is not always the case!). With a function, we can name a section of the code and conveniently call it from other part of the code.

In [ ]:
def Fibonacci(n):
  phi = (1 + math.sqrt(5)) / 2
  return round((phi ** n - (-phi) ** -n) / math.sqrt(5))

In [ ]:
print(Fibonacci(10))
print(Fibonacci(20))
print(Fibonacci(5))

55
6765
5


The result is a much simpler code! This also makes the code easier to read, since a code segment is clearly named. In the Homeworks, you are given a lot of empty functions and you will need to implement them.

Of course, a function can be more complicated than this. As another example, let's try to check if an integer is a prime number (which is a solution to the other exercise). A naive implementation will be:

In [ ]:
def is_prime(n):
  if n < 2:
    return False
  for i in range(2, n):
    if n % i == 0:
      return False
  return True

In [ ]:
for i in range(1, 51):
  if is_prime(i):
    print(i, end=" ")

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 

There is of course a much better implementation than this, but this works (although inefficiently). This shows that a function can be more complicated than the previous example.

### ⭐ **Exercise 3**
Write a function `prime` that accepts a number `n` as parameter and returns the `n`-th prime number. For example, if we call `prime(5)`, it should return `11` because the first 5 prime numbers are 2, 3, 5, 7, 11. You can call the `is_prime` function from the previous section from your function.

In [ ]:
def prime(n):
  # your code here. remove the line below.
  raise NotImplementedError

In [ ]:
# Call your function from here.

### 9 Recursion

Similar to in Mathematics, we can implement a function that calls itself. For example in the case of Fibonacci number.


In [ ]:
def Fibonacci(n):
  if n < 2:
    return 1
  return Fibonacci(n - 2) + Fibonacci(n - 1)

In [ ]:
for i in range(1, 11):
  print(Fibonacci(i), end=" ")

1 1 2 3 5 8 13 21 34 55 